[package]
name = "nc-gcode-interpreter"
version = "0.0.0-dev"
edition = "2021"

[lib]
name = "nc_gcode_interpreter"
crate-type = ["cdylib"]

[dependencies]
csv = "1.3.0"
pest = "2.7.14"
pest_derive = "2.7.14"
thiserror = "1.0.65"
clap = { version = "4.5", features = ["derive"] }
pyo3 = { version = "0.22.5" }
polars = { version = "0.43.1", features = ["csv", "lazy", "round_series", "polars-ops", "concat_str" ,"strings"] }

pyo3-polars = "0.17.0"
