# Generate src/modal_groups.rs from ggroups.json: the single source of truth
# for the G-command vocabulary. Replaces the former generate_pest.py (grammar
# literal walls) and generate_modal_ggroups.py (group-name arrays): the
# grammar now only recognizes the lexical *shapes* of G commands, and the
# interpreter classifies them against this table.
#
# Run from the repository root or this directory:
#   python ggroups/generate_g_commands.py
from pathlib import Path
import json

json_file = Path(__file__).parent.parent / "python/nc_gcode_interpreter/ggroups.json"
out_file = Path(__file__).parent.parent / "src/modal_groups.rs"

with open(json_file, "r") as file:
    g_groups = json.load(file)

modal = [g["short_name"] for g in g_groups if g["effectiveness"] == "modal"]
non_modal = [g["short_name"] for g in g_groups if g["effectiveness"] != "modal"]

lines = [
    "// Auto-generated by ggroups/generate_g_commands.py from",
    "// python/nc_gcode_interpreter/ggroups.json - do not edit by hand.",
    "",
    "/// Classify an (uppercased) G-command word: the G-group column it",
    "/// belongs to, and whether that group is modal. `None` means the word",
    "/// is not a known G command.",
    "pub fn classify_g_command(word: &str) -> Option<(&'static str, bool)> {",
    "    Some(match word {",
]
for group in g_groups:
    name = group["short_name"]
    is_modal = "true" if group["effectiveness"] == "modal" else "false"
    ids = " | ".join(f'"{e["id"].upper()}"' for e in group["entries"])
    lines.append(f'        {ids} => ("{name}", {is_modal}),')
lines += [
    "        _ => return None,",
    "    })",
    "}",
    "",
    f"pub const MODAL_G_GROUPS: [&str; {len(modal)}] = [",
    *(f'    "{g}",' for g in modal),
    "];",
    "",
    f"pub const NON_MODAL_G_GROUPS: [&str; {len(non_modal)}] = [",
    *(f'    "{g}",' for g in non_modal),
    "];",
    "",
]
out_file.write_text("\n".join(lines))
print(f"wrote {out_file} ({len(g_groups)} groups, {sum(len(g['entries']) for g in g_groups)} commands)")
