name: Build and Release Rust

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  contents: read

env:
  PROJECT_NAME: "nc-gcode-interpreter"

jobs:
  build:
    # Set the job to run on the platform specified by the matrix below
    runs-on: ${{ matrix.runner }}
 
    # Define the build matrix for cross-compilation
    strategy:
      matrix:
        include:
          - name: linux-amd64
            runner: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          # - name: linux-arm64
          #   runner: ubuntu-latest
          #   target: aarch64-unknown-linux-gnu
          # - name: win-amd64
          #   runner: windows-latest
          #   target: x86_64-pc-windows-msvc
          # - name: win-arm64
          #   runner: windows-latest
          #   target: aarch64-pc-windows-msvc
          # - name: macos-amd64
          #   runner: macos-latest
          #   target: x86_64-apple-darwin
          # - name: macos-arm64
          #   runner: macos-latest
          #   target: aarch64-apple-darwin

    # The steps to run for each matrix item
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: "${{ matrix.target }}"

      - name: Install cross-compilation tools for Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu
        
      - name: Setup Cache
        uses: Swatinem/rust-cache@v2

      - name: Build Binary
        run: cargo build --verbose --locked --release --target ${{ matrix.target }}
        env:
          CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER: aarch64-linux-gnu-gcc

      - name: Release Binary
        shell: bash
        run: |
          BIN_SUFFIX=""
          if [[ "${{ matrix.runner }}" == "windows-latest" ]]; then
            BIN_SUFFIX=".exe"
          fi

          # The built binary output location
          BIN_OUTPUT="target/${{ matrix.target }}/release/${PROJECT_NAME}${BIN_SUFFIX}"

          # Define a better name for the final binary
          BIN_RELEASE="${PROJECT_NAME}-${{ matrix.name }}${BIN_SUFFIX}"
          BIN_RELEASE_VERSIONED="${PROJECT_NAME}-${{ github.ref_name }}-${{ matrix.name }}${BIN_SUFFIX}"

          # Move the built binary where you want it
          mkdir -p artifacts
          mv "${BIN_OUTPUT}" "artifacts/${BIN_RELEASE_VERSIONED}"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}
          path: artifacts/*
